### ISSUE TITLE
Long-Baseline View Planning Upgrades

### ISSUE THREAD

**Issue by chris-traxler** [vrvis/PRo3D#404]
The View Planner should be extended to support instruments of the Curiosity rover.

**Tasks**

- [x] Support refined MSL Mastcam camera models --> trivial / already solved
- [x] Include MSL MAHLI camera model --> Modified to ChemCam RMI: JR to provide camera model once ready
- [x] Allow target-based selection of pan-tilt values. This means that these camera parameters are associated with targets and when selecting one on the surface, the camera’s orientation is set automatically.
