### ISSUE TITLE
Cross Site Correlations

### ISSUE THREAD

**Issue by chris-traxler** [vrvis/PRo3D#406]
Support analysis of correlations between different surface locations. A special version of PRo3D already supports creation of geological logs from annotated bedding contacts (stratigraphic layer boundaries) and combine them into correlation panels. Here a new tool should be developed based on extrapolation planes (e.g., from dip & strike measurements) for each analysis location. It should then be possible to display planes from several locations to investigate their intersection pattern and from that derive geologic relations. 

**Tasks**

- [ ] Generate plane from selected dip & strike measurements (discs)
- [ ] Allow fine adjustment of these planes (orientation, position) to correct for dip & strike measurement uncertainties. 
  - [ ] Allow import and export of the planes
  - [ ] Allow to define an unconstricted extension of the planes
  - [ ] Realize synergy with Dibit8 and vice versa
- [ ] Extend UI to group (via hierarchical structures) and mark correlated planes from different locations, for example by assigning colours, patterns or labels. In this way dependencies between locations can be highlighted.
- [ ] Visibilities and annotation settings shall be reflected in sequenced bookmarks

**Comment by chris-traxler** [comment]
Extension of DnS: Extend discs.
<img width="892" alt="image" src="https://github.com/user-attachments/assets/8861645d-aeaa-4f45-94c6-efca092732b0">

**Comment by sophie-sudoku** [comment]
Outcome of meeting with Rob:
Instead of generating planes from DnS planes we will extrude a curve to generate an uneven surface
