### ISSUE TITLE
Release 2021-May-19

### ISSUE THREAD

**Issue by chris-traxler** [vrvis/PRo3D#59]
This release integrates the following features:
- [x] Scalebar integration (issue #10)
- [x] Import and Visualization of "SceneObjects" (issue #13)
- [x] Geologic Surface Creation (issue #19)
- [x] Mastcam-Z Improvements (issue #53)
- [x] Adjust Focal Length (issue #54)
- [x] Flip Z direction for surfaces and scene objects
- [x] v1 for scene (also working for v0)
- [x] Super slow annotations (issue #60)

bugfixes:
- [x] Update navigationMode and exploreCenter in SaveScene and LoadScene
- [x] Import obj
- [x] LatLonAlt output sequence changed
- [x] isSurfaceFolder is always false for objs (in Surfaces) so the red exclamation icon in the little surface menu is shown

**Comment by LauraFritz14** [comment]
**Branch:** develop
**Commit:** 6d7283d

![release](https://user-images.githubusercontent.com/24911426/119807881-dbd5af00-bee3-11eb-9712-36925271aa9e.png)

**Comment by LauraFritz14** [comment]
**Branch:** develop
**Commit**: 25fd054 

added features/bugfixes:
- [x] Flip Z direction for surfaces and scene objects
- [x] LatLonAlt output sequence changed
- [x] isSurfaceFolder is always false for objs (in Surfaces) so the red exclamation icon in the little surface menu is shown

![flipZ](https://user-images.githubusercontent.com/24911426/121372163-5d92f700-c93e-11eb-8c73-b0a071f37de0.png)

**Comment by LauraFritz14** [comment]
**Branch:** develop
**Commit**: 4167030 

update: change renderpass for scalebar outline + merge with annotation updates by @haraldsteinlechner 

![img](https://user-images.githubusercontent.com/24911426/121662918-2a6b7780-caa6-11eb-9d9a-697e326c6438.png)

**Comment by chris-traxler** [comment]
All new features and bug fixes of this release (listed above) were successfully tested.
